version: '3.8'

services:
  db:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=genx_platform
   

    networks:
      - api-network

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 3333:3333
    volumes:
      - ./src:/app/src 
    networks:
      - api-network

networks:
  api-network:
    driver: bridge